### ISSUE TITLE
Create Minimal UI For Log In Page

### ISSUE THREAD

**Issue by Lierloki** [ParadineG/Tradent#2]

**Comment by esinkalay** [comment]
Login Page:
![screenshot 2018-04-07 11 22 54](https://user-images.githubusercontent.com/36517320/38452936-67a37c80-3a56-11e8-96d6-dc38c3006134.png)
Registration Page:
![screenshot 2018-04-07 11 23 14](https://user-images.githubusercontent.com/36517320/38452937-67bdafce-3a56-11e8-84db-305cba198692.png)
